### ISSUE TITLE
Wrong output in "doctor probability"

### ISSUE THREAD

**Issue by mohityadav7** [Shubham-Balhara/Practice#1]
In your solution "doctor probability", the output for the following input should be 3 but your code gives 6

> 1
6 10
10
1 2 0.3
1 3 0.7
3 3 0.2
3 4 0.8
2 4 1
4 5 0.9
4 4 0.1
5 6 1.0
6 3 0.5
6 6 0.5 

Also you are not outputting the probabilities of the most probable last division.

Two sample test cases from [this page on careercup](https://www.careercup.com/question?id=5762787884662784):
input 1:

> 1
6 10
40
1 2 0.3
1 3 0.7
3 3 0.2
3 4 0.8
2 4 1
4 5 0.9
4 4 0.1
5 6 1.0
6 3 0.5
6 6 0.5 

output 1:

> 6 0.774000 

input 2:

> 1
6 10
10
1 2 0.3
1 3 0.7
3 3 0.2
3 4 0.8
2 4 1
4 5 0.9
4 4 0.1
5 6 1.0
6 3 0.5
6 6 0.5 

output 2:

> 3 0.700000

Though I'm not sure if these test cases are correct.

**Comment by Shubham-Balhara** [comment]
during the 'dp' declaration and initialization i have interchanged the position of 'moves' and 'nodes' that's why their was a problem. i have fixed it try it now.
